#!/bin/bash
# If you get permissions error, run this
# chmod ug+x npm-i
clear

echo 'Installing dependency libraries'
echo 'Node version '
node -v
# nvm use 16
# node -v

cd ./packages/firebase-ts
npm i --legacy-peer-deps

cd ./fuctions
npm i --legacy-peer-deps
