#!/bin/bash
# chmod ug+x start
clear
echo "Starting Server Side Rendering "

ttab -t 'shared' -d ./packages/shared npm run start
ttab -t 'root-config' -d ./packages/root-config npm run start
ttab -t 'watch' -d ./packages/firebase-ts/functions tsc-watch
ttab -t 'functions' -d ./packages/firebase-ts/functions npm run serve

echo "http://localhost:5001/listingslab-app/us-central1/SSR"
